apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-apikey
  namespace: ${KUBE_NAMESPACE}
config:
    key_names:
      - X-VTEX-API-AppToken
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    # es necesario declara el ingress class
    # según corresponda, así kong podrá procesarlo
    kubernetes.io/ingress.class: api-gw
username: ${CI_PROJECT_NAME}
custom_id: ${CI_PROJECT_NAME}
credentials:
  - ${CI_PROJECT_NAME}-key
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-key
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: key-auth
  key: ${KONG_API_KEY}
