apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
username: ${CI_PROJECT_NAME}
custom_id: ${CI_PROJECT_NAME}
credentials:
  - ${CI_PROJECT_NAME}-key
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ${CI_PROJECT_NAME}-internal
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw-internal
username: ${CI_PROJECT_NAME}-internal
custom_id: ${CI_PROJECT_NAME}-internal
credentials:
  - ${CI_PROJECT_NAME}-key
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-apitoken
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
config:
  key_names:
    - X-VTEX-API-AppToken
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-apitoken-internal
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw-internal
config:
  key_names:
    - X-VTEX-API-AppToken
plugin: key-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-key
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: key-auth
  key: ${KONG_APPTOKEN}
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
plugin: acl
config:
  whitelist:
    - ${CI_PROJECT_NAME}-access
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: acl
  group: ${CI_PROJECT_NAME}-access
