apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-apikey
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
config:
  header_name: X-VTEX-API-AppToken
  rename:
    headers:
      - apikey: X-VTEX-API-AppToken
  key_names:
    - X-VTEX-API-AppToken
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
  annotation:
    kubernetes.io/ingress.class: api-gw
plugin: acl
config:
  whitelist:
  - ${CI_PROJECT_NAME}-access
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ${CI_PROJECT_NAME}-endpoint
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
proxy:
  path: /
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: acl
  group: ${CI_PROJECT_NAME}-access
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-consumer-key
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: key-auth
  key: ${KONG_API_KEY}
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
username: ${CI_PROJECT_NAME}
custom_id: ${CI_PROJECT_NAME}
credentials:
  - ${CI_PROJECT_NAME}-consumer-key
  - ${CI_PROJECT_NAME}-acl
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-example
config:
  remove:
    headers:
      - apikey
      - X-VTEX-API-AppToken
plugin: request-transformer
