apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-vtexapptoken
  namespace: ${KUBE_NAMESPACE}
config:
  key_names:
    - X-VTEX-API-AppToken
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: ${CI_PROJECT_NAME}-consumer-apptoken
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: api-gw
    konghq.com/plugins: ${CI_PROJECT_NAME}-vtexapptoken
username: ${CI_PROJECT_NAME}-2
custom_id: ${CI_PROJECT_NAME}-2
credentials:
  - ${CI_PROJECT_NAME}-apptoken
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-apptoken
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: key-auth
  key: ${KONG_APPTOKEN}
