apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "api-gw-pub"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    konghq.com/override: "strip"
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  rules:
    - host: ${CI_PROJECT_NAME}.${ENDPOINT}
      http:
        paths:
          - path: /api
            backend:
              serviceName: ${CI_PROJECT_NAME}
              servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress # Ruta
metadata:
  name: ${CI_PROJECT_NAME}-payments
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "api-gw"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    konghq.com/override: "strip"
    konghq.com/plugins: "${CI_PROJECT_NAME}-acl,${CI_PROJECT_NAME}-vtexapptoken"
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  rules:
    - host: ${CI_PROJECT_NAME}.${ENDPOINT}
      http:
        paths:
          - path: /api/payments
            backend:
              serviceName: ${CI_PROJECT_NAME}-payments
              servicePort: http
