apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    konghq.com/plugins: "api-key"
    kubernetes.io/ingress.class: "api-gw"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  rules:
    - host: ${CI_PROJECT_NAME}.${ENDPOINT}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${CI_PROJECT_NAME}
              servicePort: http
