apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${CI_PROJECT_NAME}
  namespace: ${KUBE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "api-gw"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    konghq.com/strip-path: "true"
    konghq.com/plugins: "${CI_PROJECT_NAME}-apikey"
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  rules:
    - host: ${CI_PROJECT_NAME}.${ENDPOINT}
      http:
        paths:
          - path: /payments/
            backend:
              serviceName: ${CI_PROJECT_NAME}
              servicePort: http
