apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
  annotation:
    kubernetes.io/ingress.class: api-gw
plugin: acl
config:
  whitelist:
    - ${CI_PROJECT_NAME}-access
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-acl
  namespace: ${KUBE_NAMESPACE}
stringData:
  kongCredType: acl
  group: ${CI_PROJECT_NAME}-access
